name: Latest blog post workflow
on:
  schedule:
    # Runs every night at 2 am
    - cron: "0 2 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          readme_path: "./profile/README.md"
          feed_list: "https://blogs.lamplitlabs.com/feed.xml"
